[pyprland]
plugins = ["scratchpads", "shortcuts_menu"]

# using variables for demonstration purposes (not needed)
[pyprland.variables]
term_classed = "kitty --class"

[scratchpads.term]
animation = "fromTop"
command = "[term_classed] main-dropterm"
class = "main-dropterm"
size = "75% 60%"
max_size = "1920px 100%"

[scratchpads.proton-pass]
animation = "fromTop"
command = "proton-pass"
size = "75% 60%"
max_size = "1920px 100%"
class = "Proton Pass"

[shortcuts_menu.entries]
"Color picker" = [
    { name = "format", options = [
        "hex",
        "rgb",
        "hsv",
        "hsl",
        "cmyk",
    ] },
    "sleep 0.2; hyprpicker --format [format] | wl-copy", # sleep to let the menu close before the picker opens
]
"foobar" = "ls"